del "arial.ttf" >nul
del "arialbd.ttf" >nul
del "arialbi.ttf" >nul
del "ariali.ttf" >nul
del "ariblk.ttf" >nul
del "comic.ttf" >nul
del "comicbd.ttf" >nul
del "cour.ttf" >nul
del "courbd.ttf" >nul
del "courbi.ttf" >nul
del "couri.ttf" >nul
del "estre.ttf" >nul
del "framd.ttf" >nul
del "framdit.ttf" >nul
del "gautami.ttf" >nul
del "georgia.ttf" >nul
del "georgiab.ttf" >nul
del "georgiai.ttf" >nul
del "georgiaz.ttf" >nul
del "impact.ttf" >nul
del "kartika.ttf" >nul
del "latha.ttf" >nul
del "lsans.ttf" >nul
del "lsansd.ttf" >nul
del "lsansdi.ttf" >nul
del "lsansi.ttf" >nul
del "lucon.ttf" >nul
del "l_10646.ttf" >nul
del "mangal.ttf" >nul
del "micross.ttf" >nul
del "modern.fon" >nul
del "mvboli.ttf" >nul
del "pala.ttf" >nul
del "palab.ttf" >nul
del "palabi.ttf" >nul
del "palai.ttf" >nul
del "raavi.ttf" >nul
del "roman.fon" >nul
del "script.fon" >nul
del "shruti.ttf" >nul
del "sylfaen.ttf" >nul
del "symbol.ttf" >nul
del "tahoma.ttf" >nul
del "tahomabd.ttf" >nul
del "times.ttf" >nul
del "timesbd.ttf" >nul
del "timesbi.ttf" >nul
del "timesi.ttf" >nul
del "trebuc.ttf" >nul
del "trebucbd.ttf" >nul
del "trebucbi.ttf" >nul
del "trebucit.ttf" >nul
del "tunga.ttf" >nul
del "verdana.ttf" >nul
del "verdanab.ttf" >nul
del "verdanai.ttf" >nul
del "verdanaz.ttf" >nul
del "vrinda.ttf" >nul
del "webdings.ttf" >nul
del "wingding.ttf" >nul
del "wst_czec.fon" >nul
del "wst_engl.fon" >nul
del "wst_fren.fon" >nul
del "wst_germ.fon" >nul
del "wst_ital.fon" >nul
del "wst_span.fon" >nul
del "wst_swed.fon" >nul